package identitymodel

import (
	"context"
	"time"
)

// TOTPProvider provides TOTP secret generation and code validation.
// Implemented by github.com/larsartmann/cqrs-htmx/usermgmt/totp/v4.Provider.
// The interface uses only primitive types so the implementation module does
// not need to import core usermgmt.
type TOTPProvider interface {
	// GenerateSecret creates a new TOTP secret for the given account name.
	// Returns the raw secret bytes (for storage), the base32-encoded secret
	// (for display to the user), and the otpauth:// URI (for QR codes).
	GenerateSecret(accountName string) (rawSecret []byte, base32Secret, otpauthURI string, err error)

	// ValidateCode checks if the given code is valid for the provided raw
	// secret bytes.
	ValidateCode(rawSecret []byte, code string) bool
}

// WebAuthnProvider defines the WebAuthn (passkey) authentication contract.
// Implemented by usermgmt/webauthn.Provider (v4).
//
// All parameters use []byte / json.RawMessage to avoid importing go-webauthn's
// protocol types in the core package. The implementation handles serialization.
//
// userJSON contains serialized user data (id, email, display_name, credentials).
// options contains the ceremony options as JSON (CredentialCreation / CredentialAssertion).
// sessionData contains opaque serialized session state (stored by the Service).
// credentialJSON contains the new credential data as JSON.
// body contains the raw authenticator response body.
type WebAuthnProvider interface {
	// BeginRegistration starts the credential registration ceremony.
	// Returns the CredentialCreation options (as JSON) and opaque session data.
	BeginRegistration(ctx context.Context, userJSON []byte) (options, sessionData []byte, err error)

	// FinishRegistration completes the credential registration ceremony.
	// Returns the new credential data as JSON.
	FinishRegistration(ctx context.Context, userJSON, body, sessionData []byte) (credentialJSON []byte, err error)

	// BeginLogin starts the authentication ceremony.
	// Returns the CredentialAssertion options (as JSON) and opaque session data.
	BeginLogin(ctx context.Context, userJSON []byte) (options, sessionData []byte, err error)

	// FinishLogin completes the authentication ceremony.
	FinishLogin(ctx context.Context, userJSON, body, sessionData []byte) error
}

// OAuth2Provider defines the OAuth2/OIDC authentication contract.
// Implemented by usermgmt/oauth2.Provider (v4).
//
// All parameters use primitive types so the implementation module does not
// import core usermgmt. The provider generates PKCE internally.
type OAuth2Provider interface {
	// BeginLogin generates PKCE and builds the authorization URL for the given
	// provider. state is the CSRF state token (generated by the Service).
	// Returns the redirect URL and PKCE verifier (stored by the Service).
	BeginLogin(ctx context.Context, providerName, state string) (redirectURL, pkceVerifier string, err error)

	// FinishLogin exchanges the authorization code for tokens and extracts
	// user info. Returns the user info as JSON (subject, email, email_verified,
	// display_name).
	FinishLogin(ctx context.Context, providerName, code, pkceVerifier string) (userInfoJSON []byte, err error)
}

// OAuth2UserInfo is the normalized user information returned by an OAuth2
// provider after token exchange.
type OAuth2UserInfo struct {
	Subject       string `json:"subject"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	DisplayName   string `json:"display_name"`
}

// WebAuthnSessionStore manages WebAuthn challenge session data as opaque bytes.
// The provider serializes *webauthn.SessionData to []byte; the store is
// transport-agnostic and does not import go-webauthn.
// The default in-memory implementation is suitable for single-process deployments.
// Implement this interface with Redis or SQL for multi-instance deployments.
type WebAuthnSessionStore interface {
	Save(key string, data []byte)
	Get(key string) ([]byte, error)
	Delete(key string)
}

// VerificationTokenStore manages email verification tokens.
// The default in-memory implementation is suitable for single-process deployments.
// Implement this interface with Redis or SQL for multi-instance deployments.
type VerificationTokenStore interface {
	Save(userID UserID, email string, ttl time.Duration) (string, error)
	Consume(token string) (UserID, error)
}

// LockoutStore tracks failed authentication attempts and enforces temporary account lockout.
// The default in-memory implementation is suitable for single-process deployments.
// Implement this interface with Redis or SQL for distributed lockout across instances.
type LockoutStore interface {
	IsLocked(email string) bool
	RecordFailure(email string) bool
	Reset(email string)
}

// PendingTOTPStore manages pending TOTP setup secrets during the enable-TOTP ceremony.
// The default in-memory implementation is suitable for single-process deployments.
// Implement this interface with Redis or SQL for multi-instance deployments.
type PendingTOTPStore interface {
	Save(userID string, secret []byte, ttl time.Duration)
	Consume(userID string) ([]byte, bool)
}
