package datastar

import (
	"net/http"

	sdk "github.com/starfederation/datastar-go/datastar"
)

// Response builds a Datastar SSE response for a single HTTP request. Unlike
// the Broadcaster (which streams patches to many clients over time), Response
// writes patches immediately to one client and returns.
//
// All methods return *Response for fluent chaining. Patches are sent
// immediately via the Datastar SSE protocol (write-through — no buffering).
//
//	ds.NewResponse(w, r).
//	    PatchSignals(map[string]any{"title": ""}).
//	    PatchElements(renderTodoList(todos), ds.WithSelectorID("todo-list"), ds.WithModeInner())
type Response struct {
	sse *sdk.ServerSentEventGenerator
}

// NewResponse creates a Datastar SSE response writer. This upgrades the
// HTTP connection to text/event-stream and prepares it for sending Datastar
// patches.
func NewResponse(w http.ResponseWriter, r *http.Request) *Response {
	return &Response{sse: sdk.NewSSE(w, r)}
}

// PatchSignals updates the client's reactive signals. The signals argument
// can be any JSON-marshallable value.
func (resp *Response) PatchSignals(signals any, opts ...PatchSignalsOption) *Response {
	_ = resp.sse.MarshalAndPatchSignals(signals, opts...)

	return resp
}

// PatchSignalsIfMissing sets signals only if they don't already exist on
// the client.
func (resp *Response) PatchSignalsIfMissing(signals any, opts ...PatchSignalsOption) *Response {
	_ = resp.sse.MarshalAndPatchSignalsIfMissing(signals, opts...)

	return resp
}

// PatchElements morphs HTML elements into the client's DOM.
func (resp *Response) PatchElements(html string, opts ...PatchElementOption) *Response {
	_ = resp.sse.PatchElements(html, opts...)

	return resp
}

// PatchElementsTempl renders a templ component into the client's DOM.
func (resp *Response) PatchElementsTempl(component TemplComponent, opts ...PatchElementOption) *Response {
	_ = resp.sse.PatchElementTempl(component, opts...)

	return resp
}

// RemoveElement removes DOM elements matching the CSS selector.
func (resp *Response) RemoveElement(selector string) *Response {
	_ = resp.sse.RemoveElement(selector)

	return resp
}

// Redirect navigates the client to the given URL.
func (resp *Response) Redirect(url string) *Response {
	_ = resp.sse.Redirect(url)

	return resp
}

// ExecuteScript runs JavaScript on the client.
func (resp *Response) ExecuteScript(script string, opts ...ExecuteScriptOption) *Response {
	_ = resp.sse.ExecuteScript(script, opts...)

	return resp
}

// ApplyPatches applies a slice of Patch values to the client. This is useful
// for replaying patches generated by the EventBridge or stored externally.
func (resp *Response) ApplyPatches(patches ...Patch) *Response {
	_ = applyAll(resp.sse, patches)

	return resp
}

// Apply is a no-op provided for API symmetry with cqrshtmx.Response.Apply().
// Datastar SSE patches are write-through (sent immediately, not buffered),
// so there is nothing to flush.
func (resp *Response) Apply() *Response {
	return resp
}

// SSE returns the underlying Datastar SSE generator for advanced use cases
// that need direct SDK access.
func (resp *Response) SSE() *sdk.ServerSentEventGenerator {
	return resp.sse
}
