package usermgmt

import (
	"context"
)

// Auth strategy interfaces — v4 Sollbruchstelle seam design.
//
// These interfaces define the contract between the core Service and the three
// optional auth strategy implementations (TOTP, WebAuthn, OAuth2). In v4,
// consumers import only the auth strategies they need:
//
//	import usermgmt           // core user management
//	import usermgmt/totp      // TOTP MFA (pulls pquerna/otp)
//	import usermgmt/webauthn  // passkey auth (pulls go-webauthn)
//	// consumer does NOT import usermgmt/oauth2 if they don't need it
//
// The interfaces use primitive types ([]byte, string) so the implementations
// can live in separate modules without importing core usermgmt.

// TOTPProvider provides TOTP secret generation and code validation.
// Implemented by github.com/larsartmann/cqrs-htmx/usermgmt/totp/v4.Provider.
// The interface uses only primitive types so the implementation module does
// not need to import core usermgmt.
type TOTPProvider interface {
	// GenerateSecret creates a new TOTP secret for the given account name.
	// Returns the raw secret bytes (for storage), the base32-encoded secret
	// (for display to the user), and the otpauth:// URI (for QR codes).
	GenerateSecret(accountName string) (rawSecret []byte, base32Secret, otpauthURI string, err error)

	// ValidateCode checks if the given code is valid for the provided raw
	// secret bytes.
	ValidateCode(rawSecret []byte, code string) bool
}

// WebAuthnProvider defines the WebAuthn (passkey) authentication contract.
// Implemented by usermgmt/webauthn.Provider (v4).
//
// All parameters use []byte / json.RawMessage to avoid importing go-webauthn's
// protocol types in the core package. The implementation handles serialization.
//
// userJSON contains serialized user data (id, email, display_name, credentials).
// options contains the ceremony options as JSON (CredentialCreation / CredentialAssertion).
// sessionData contains opaque serialized session state (stored by the Service).
// credentialJSON contains the new credential data as JSON.
// body contains the raw authenticator response body.
type WebAuthnProvider interface {
	// BeginRegistration starts the credential registration ceremony.
	// Returns the CredentialCreation options (as JSON) and opaque session data.
	BeginRegistration(ctx context.Context, userJSON []byte) (options, sessionData []byte, err error)

	// FinishRegistration completes the credential registration ceremony.
	// Returns the new credential data as JSON.
	FinishRegistration(ctx context.Context, userJSON, body, sessionData []byte) (credentialJSON []byte, err error)

	// BeginLogin starts the authentication ceremony.
	// Returns the CredentialAssertion options (as JSON) and opaque session data.
	BeginLogin(ctx context.Context, userJSON []byte) (options, sessionData []byte, err error)

	// FinishLogin completes the authentication ceremony.
	FinishLogin(ctx context.Context, userJSON, body, sessionData []byte) error
}

// OAuth2Provider defines the OAuth2/OIDC authentication contract.
// Implemented by usermgmt/oauth2.Provider (v4).
//
// All parameters use primitive types so the implementation module does not
// import core usermgmt. The provider generates PKCE internally.
type OAuth2Provider interface {
	// BeginLogin generates PKCE and builds the authorization URL for the given
	// provider. state is the CSRF state token (generated by the Service).
	// Returns the redirect URL and PKCE verifier (stored by the Service).
	BeginLogin(ctx context.Context, providerName, state string) (redirectURL, pkceVerifier string, err error)

	// FinishLogin exchanges the authorization code for tokens and extracts
	// user info. Returns the user info as JSON (subject, email, email_verified,
	// display_name).
	FinishLogin(ctx context.Context, providerName, code, pkceVerifier string) (userInfoJSON []byte, err error)
}

// OAuth2UserInfo is the normalized user information returned by an OAuth2
// provider after token exchange. Used by the Service to deserialize the
// provider's JSON return value.
type OAuth2UserInfo struct {
	Subject       string `json:"subject"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	DisplayName   string `json:"display_name"`
}
