package usermgmt

import (
	"sync"
	"time"
)

// defaultOAuthStateTTL is the default lifetime of an OAuth2 state token.
const defaultOAuthStateTTL = 10 * time.Minute

// oauthStateEvictionInterval is how often expired OAuth state tokens are cleaned up.
const oauthStateEvictionInterval = 5 * time.Minute

// OAuth2StateStore is the persistence interface for OAuth2 CSRF state tokens.
// Implementations must ensure state tokens are single-use and expire after the
// configured TTL. The default in-memory implementation is suitable for
// single-instance deployments; use Redis or a shared store for multi-instance.
type OAuth2StateStore interface {
	// Save stores a pre-generated state token with the provider name and
	// PKCE verifier. The state token is generated by the caller.
	Save(state, provider, pkceVerifier string, ttl time.Duration) error
	// Consume validates and deletes the state token (one-time use).
	// Returns the stored provider name and PKCE verifier.
	Consume(state string) (provider, pkceVerifier string, err error)
	// EvictExpired removes all expired state tokens. Returns the count evicted.
	EvictExpired() int
}

type oauth2StateEntry struct {
	provider     string
	pkceVerifier string
	expiresAt    time.Time
}

type oauth2StateStore struct {
	mu     sync.Mutex
	states map[string]oauth2StateEntry
}

func newOAuth2StateStore() *oauth2StateStore {
	return &oauth2StateStore{ //nolint:exhaustruct // mu is zero-value (sync.Mutex)
		states: make(map[string]oauth2StateEntry),
	}
}

// Save stores a pre-generated state token with the provider name and
// PKCE verifier.
func (s *oauth2StateStore) Save(state, provider, pkceVerifier string, ttl time.Duration) error {
	s.mu.Lock()
	s.states[state] = oauth2StateEntry{
		provider:     provider,
		pkceVerifier: pkceVerifier,
		expiresAt:    time.Now().Add(ttl),
	}
	s.mu.Unlock()
	return nil
}

// Consume validates and deletes the state token (one-time use).
// Returns the stored provider name and PKCE verifier.
func (s *oauth2StateStore) Consume(state string) (provider, pkceVerifier string, err error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	entry, ok := s.states[state]
	if !ok {
		return "", "", ErrOAuthInvalidState
	}
	delete(s.states, state)
	if time.Now().After(entry.expiresAt) {
		return "", "", ErrOAuthInvalidState
	}
	return entry.provider, entry.pkceVerifier, nil
}

// EvictExpired removes all expired state tokens. Returns the count evicted.
func (s *oauth2StateStore) EvictExpired() int {
	return evictExpired(&s.mu, s.states, func(_ string, e oauth2StateEntry) bool {
		return time.Now().After(e.expiresAt)
	})
}

func generateOAuth2State() (string, error) {
	return randomBase64URLString(32, "oauth2 state")
}
