#!/usr/bin/env bash
# test-check-streamid-identity.sh — fixture self-test for
# check-streamid-identity.sh (D12 / gotcha-25 guard).
#
# Cases:
#   1. pinned display site, exact count        -> exit 0
#   2. unpinned identity-position site         -> exit 1, names the file
#   3. count drift in a pinned file            -> exit 1
#   4. zero candidates anywhere                -> exit 1 (fail-loud-on-zero)
#   5. *_test.go / *_templ.go sites excluded   -> only non-excluded counted
#
# Usage: bash scripts/selftests/test-check-streamid-identity.sh
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GATE="$SCRIPT_DIR/../checks/check-streamid-identity.sh"

WORK="$(mktemp -d /tmp/test-streamid-guard-XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

pass=0
fail=0

run_gate() {
  STREAMID_GUARD_ROOT="$1" bash "$GATE" 2>&1
}

check() { # check <case-no> <expect-rc:0|1> <grep-needle> <output> <rc>
  local no="$1" want_rc="$2" needle="$3" out="$4" rc="$5"
  if [ "$rc" -eq 0 ] && [ "$want_rc" != "0" ]; then
    echo "  FAIL $no: expected failure, gate passed; output:" >&2
    printf '%s\n' "$out" | sed 's/^/      /' >&2
    fail=$((fail + 1))
    return
  fi
  if [ "$rc" -ne 0 ] && [ "$want_rc" = "0" ]; then
    echo "  FAIL $no: expected pass, gate failed; output:" >&2
    printf '%s\n' "$out" | sed 's/^/      /' >&2
    fail=$((fail + 1))
    return
  fi
  if [ -n "$needle" ] && ! printf '%s' "$out" | grep -q "$needle"; then
    echo "  FAIL $no: output missing '$needle'; output:" >&2
    printf '%s\n' "$out" | sed 's/^/      /' >&2
    fail=$((fail + 1))
    return
  fi
  echo "  ok $no"
  pass=$((pass + 1))
}

# Case 1: pinned display site with exact expected count passes.
mkdir -p "$WORK/clean/transport"
printf 'package transport\n\nvar _ = evt.StreamID().String()\n' >"$WORK/clean/transport/event_sse.go"
out=$(run_gate "$WORK/clean")
rc=$?
check 1 0 "match the pinned allowlist" "$out" "$rc"

# Case 2: identity-position derivation in an unpinned file fails, file named.
mkdir -p "$WORK/identity/usermgmt" "$WORK/identity/transport"
printf 'package usermgmt\n\nvar _ = NewUserID(aggID.String())\n' >"$WORK/identity/usermgmt/es_readmodel.go"
printf 'package transport\n\nvar _ = evt.StreamID().String()\n' >"$WORK/identity/transport/event_sse.go"
out=$(run_gate "$WORK/identity")
rc=$?
check 2 1 "unpinned display-form StreamID site(s) in usermgmt/es_readmodel.go" "$out" "$rc"

# Case 3: count drift in a pinned file (2 sites where 1 is pinned) fails.
mkdir -p "$WORK/drift/transport"
printf 'package transport\n\nvar a = evt.StreamID().String()\n\nvar b = evt.StreamID().String()\n' >"$WORK/drift/transport/event_sse.go"
out=$(run_gate "$WORK/drift")
rc=$?
check 3 1 "count drift in pinned file transport/event_sse.go: expected 1, found 2" "$out" "$rc"

# Case 4: zero candidates fails loud (guard lost its target).
mkdir -p "$WORK/empty/transport"
printf 'package transport\n\nvar _ = evt.StreamID().Get()\n' >"$WORK/empty/transport/event_sse.go"
out=$(run_gate "$WORK/empty")
rc=$?
check 4 1 "0 candidates scanned" "$out" "$rc"

# Case 5: test and generated files are excluded from the scan.
mkdir -p "$WORK/excluded/transport"
printf 'package transport\n\nvar _ = evt.StreamID().String()\n' >"$WORK/excluded/transport/event_sse.go"
printf 'package transport\n\nvar a = evt.StreamID().String()\n\nvar b = aggID.String()\n' >"$WORK/excluded/transport/event_sse_test.go"
printf '// Code generated by templ. DO NOT EDIT.\npackage transport\n\nvar c = evt.StreamID().String()\n' >"$WORK/excluded/transport/page_templ.go"
out=$(run_gate "$WORK/excluded")
rc=$?
check 5 0 "all 1 StreamID display-form sites" "$out" "$rc"

echo "pass=$pass fail=$fail"
if [ "$fail" -ne 0 ]; then
  exit 1
fi
echo "OK: check-streamid-identity fixture self-test"
