#!/usr/bin/env bash
# test-install-git-hooks.sh — self-test for install-git-hooks.sh
#
# Exercises the installer in throwaway scratch repos (off-line, no
# buildflow binary — a stub stands in for it):
#   - --verify on a missing hook exits 2
#   - default mode refuses a diverged hook with a diff (exit 1)
#   - --force restores byte-match; default becomes idempotent
#   - core.hooksPath (repo-local) is honored as the active hook path
#   - BEHAVIOR: with the hook installed, a scratch commit succeeds past
#     the gates (stub buildflow), and a staged >1 MB file is BLOCKED
#
# Usage: ./scripts/test-install-git-hooks.sh
# Exit: 0 = all tests pass, 1 = at least one test fails

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALLER="$SCRIPT_DIR/install-git-hooks.sh"
TEMPLATE="$SCRIPT_DIR/hooks/pre-commit.template"

pass=0
fail=0

report() { # <ok 0|1> <label...>
  if [ "$1" -eq 0 ]; then
    echo "  PASS: ${*:2}"
    pass=$((pass + 1))
  else
    echo "  FAIL: ${*:2}"
    fail=$((fail + 1))
  fi
}

# Buildflow-generated baseline (what a fresh `buildflow precommit install`
# produces — i.e. the template WITHOUT the manual gate blocks).
write_baseline() {
  cat >"$1/pre-commit" <<'BASELINE'
#!/usr/bin/env bash
# BuildFlow Pre-Commit Hook
# Auto-generated by 'buildflow precommit install'
# This hook runs BuildFlow in pre-commit mode before each commit
# Performance: budget=60s, max=2m

set -e

echo "Running BuildFlow pre-commit checks (budget: 60s)..."

START=$(date +%s)

# Run buildflow in pre-commit mode with performance budget
buildflow --build-mode pre-commit --staged-only

# Re-stage files that may have been modified by formatters
# This ensures formatted code is included in the commit
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)
if [ -n "$STAGED_FILES" ]; then
    echo "$STAGED_FILES" | xargs -r git add
fi

END=$(date +%s)
DURATION=$((END-START))

echo "BuildFlow completed in ${DURATION}s"
BASELINE
  chmod +x "$1/pre-commit"
}

new_scratch() { # echoes scratch dir; repo-local hooksPath keeps the suite
  # hermetic — identical behavior with or without a global core.hooksPath
  # (CI runners have none; dev machines set .githooks globally)
  local scratch
  scratch="$(mktemp -d)"
  git -C "$scratch" init -q
  git -C "$scratch" config user.email fixture@example.com
  git -C "$scratch" config user.name fixture
  git -C "$scratch" config commit.gpgsign false
  git -C "$scratch" config core.hooksPath .githooks
  mkdir -p "$scratch/scripts/hooks" "$scratch/scripts/lib"
  cp "$TEMPLATE" "$scratch/scripts/hooks/"
  cp "$INSTALLER" "$scratch/scripts/"
  cp "$SCRIPT_DIR/check-large-files.sh" "$SCRIPT_DIR/check-release-train.sh" \
    "$SCRIPT_DIR/prewarm-gocache.sh" "$scratch/scripts/"
  cp "$SCRIPT_DIR/lib/go-cache-env.sh" "$scratch/scripts/lib/" 2>/dev/null || true
  printf '%s\n' "$scratch"
}

echo ""
echo "=== Test Suite: install-git-hooks.sh ==="
echo ""

# --- T1: --verify on missing hook -> exit 2 --------------------------------
S="$(new_scratch)"
set +e
bash "$S/scripts/install-git-hooks.sh" --verify >/dev/null 2>&1
rc=$?
set -e
report "$([ "$rc" -eq 2 ] && echo 0 || echo 1)" "T1 --verify missing hook exits 2 (got $rc)"
rm -rf "$S"

# --- T2: default mode refuses a buildflow-regenerated hook -----------------
S="$(new_scratch)"
HD="$S/.githooks"
mkdir -p "$HD"
write_baseline "$HD"
set +e
OUT="$(bash "$S/scripts/install-git-hooks.sh" 2>&1)"
rc=$?
set -e
report "$([ "$rc" -eq 1 ] && echo 0 || echo 1)" "T2 refuses diverged hook, exit 1 (got $rc)"
report "$(echo "$OUT" | grep -q -- "--force" && echo 0 || echo 1)" "T2 refusal suggests --force"
rm -rf "$S"

# --- T3: --force restores byte-match; T4: default idempotent; T5: verify ---
S="$(new_scratch)"
HD="$S/.githooks"
mkdir -p "$HD"
write_baseline "$HD"
set +e
bash "$S/scripts/install-git-hooks.sh" --force >/dev/null 2>&1
rc=$?
set -e
report "$([ "$rc" -eq 0 ] && echo 0 || echo 1)" "T3 --force exits 0"
report "$(cmp -s "$TEMPLATE" "$HD/pre-commit" && echo 0 || echo 1)" "T3 hook byte-matches template after --force"
set +e
bash "$S/scripts/install-git-hooks.sh" >/dev/null 2>&1
rc=$?
bash "$S/scripts/install-git-hooks.sh" --verify >/dev/null 2>&1
rcv=$?
set -e
report "$([ "$rc" -eq 0 ] && [ "$rcv" -eq 0 ] && echo 0 || echo 1)" "T4/T5 default idempotent + --verify OK"

# --- T6/T7: BEHAVIOR — gates actually fire on scratch commits --------------
mkdir -p "$S/bin"
printf '#!/usr/bin/env bash\nexit 0\n' >"$S/bin/buildflow"
chmod +x "$S/bin/buildflow"
git -C "$S" add scripts
echo hello >"$S/README.md"
git -C "$S" add README.md
set +e
OUT="$(cd "$S" && PATH="$S/bin:$PATH" git commit -q -m t6 2>&1)"
rc=$?
set -e
report "$([ "$rc" -eq 0 ] && echo 0 || echo 1)" "T6 scratch commit passes installed gates (got $rc: $(echo "$OUT" | tail -1))"
dd if=/dev/zero of="$S/big.bin" bs=1024 count=2048 2>/dev/null
git -C "$S" add big.bin
set +e
OUT="$(cd "$S" && PATH="$S/bin:$PATH" git commit -q -m t7 2>&1)"
rc=$?
set -e
report "$([ "$rc" -ne 0 ] && echo 0 || echo 1)" "T7 staged >1 MB file is BLOCKED by the large-file guard"
rm -rf "$S"

# --- T8: repo-local core.hooksPath is honored ------------------------------
S="$(new_scratch)"
git -C "$S" config core.hooksPath .myhooks
set +e
bash "$S/scripts/install-git-hooks.sh" --verify >/dev/null 2>&1
rc=$?
set -e
report "$([ "$rc" -eq 2 ] && echo 0 || echo 1)" "T8 --verify targets core.hooksPath (.myhooks), exits 2 when missing"
set +e
bash "$S/scripts/install-git-hooks.sh" >/dev/null 2>&1
rc=$?
set -e
report "$([ "$rc" -eq 0 ] && [ -f "$S/.myhooks/pre-commit" ] && echo 0 || echo 1)" "T8 default installs into .myhooks/"
rm -rf "$S"

echo ""
echo "Results: $pass passed, $fail failed"
echo ""

if [ "$fail" -gt 0 ]; then
  echo "FAIL: $fail test(s) failed."
  exit 1
fi

echo "All tests passed."
